# database application configuration linked to db service provide by docker-compose.yml
spring:
  jpa:
    database: POSTGRESQL
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: false
      hibernate.format_sql: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres/example_dev?schema=public
    username: exampledev
    password: exampledev
  liquibase:
    enabled: true
    contexts: 'fixture, reference'
    drop-first: true

# log
logging:
  reactor:
    enabled: false
  access:
    enabled: true
